### ISSUE TITLE
Memory leak in case PostgreSQL JDBC driver is used

### ISSUE THREAD

**Issue by dedal82** [ebean-orm/ebean-datasource#15]
The PostgreSQL JDBC driver uses a chain to save all the SQLWarnings generated during a connection is open.
https://github.com/pgjdbc/pgjdbc/blob/f3ade07d7758f134fd137db3ebab544f2211e290/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L398

All the warnings must be cleared before putting a connection back to the connection pool.
Is there a reason, why the next line of code is commented?
https://github.com/ebean-orm/ebean-datasource/blob/cc0e9df2f8ce67e1af66c96902df3ede14319918/src/main/java/io/ebean/datasource/pool/PooledConnection.java#L502

**Comment by rbygrave** [comment]
> Is there a reason, why the next line of code is commented?

Ah, no there is not - we need to put that back.

**Comment by rbygrave** [comment]
Released 4.2.2 - it is on it's way to maven central.
