### ISSUE TITLE
Deadlock, when DB is gone

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean-datasource#26]
Hello Rob, I've found possible a dead lock when the database goes down.
This happens with ebean-datasource 4.5.2 (so line numbers are slightly different latest version)

There were two threads, waiting for locks

Application thread tries to get connection, but fails and calls notifyDataSourceDown
```
ConnectionPool.notifyDataSourceIsDown(SQLException)  line: 393<-- synchronized(this)
ConnectionPool.createUnpooledConnection(Properties, boolean) line: 532	
ConnectionPool.createUnpooledConnection() line: 521	
ConnectionPool.createConnectionForQueue(int) line: 763	
PooledConnectionQueue._getPooledConnection() line: 313	<-- ReentrantLock.lockInterruptibly();
PooledConnectionQueue.getPooledConnection() line: 269	
ConnectionPool.getPooledConnection() line: 811	
ConnectionPool.getConnection() line: 799	
```
the db.heartbeat Thread tries to do the same, but in a slightly different order
```
Unsafe.park(boolean, long) line: not available [native method]	
LockSupport.park(Object) line: 175	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).parkAndCheckInterrupt() line: 836	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).acquireQueued(AbstractQueuedSynchronizer$Node, int) line: 870	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).acquire(int) line: 1199	
ReentrantLock$NonfairSync.lock() line: 209	
ReentrantLock.lock() line: 285	
PooledConnectionQueue.reset(long) line: 402	<-- ReentrantLock.lock()
ConnectionPool.reset() line: 790	
ConnectionPool.notifyDataSourceIsDown(SQLException) line: 394	<--- synchonized(this)
ConnectionPool.checkDataSource() line: 466	
ConnectionPool.access$000(ConnectionPool) line: 43	
ConnectionPool$HeartBeatRunnable.run() line: 259	
TimerThread.mainLoop() line: 555	
TimerThread.run() line: 505	
```

**investigation**

Application thread locks the reentrant lock here:
https://github.com/ebean-orm/ebean-datasource/blob/master/src/main/java/io/ebean/datasource/pool/PooledConnectionQueue.java#L293
tries to create a new connection here, which fails
https://github.com/ebean-orm/ebean-datasource/blob/master/src/main/java/io/ebean/datasource/pool/ConnectionPool.java#L528
and calls notifyDataSourceIsDown in the exception handler (which is blocked by db.heartbeat thread)
https://github.com/ebean-orm/ebean-datasource/blob/master/src/main/java/io/ebean/datasource/pool/ConnectionPool.java#L395

in the same time, the db.heartbeat thread calls notifyDataSourceIsDown here
https://github.com/ebean-orm/ebean-datasource/blob/master/src/main/java/io/ebean/datasource/pool/ConnectionPool.java#L470
and tries to reset the queue
https://github.com/ebean-orm/ebean-datasource/blob/master/src/main/java/io/ebean/datasource/pool/PooledConnectionQueue.java#L400
which tries to put a lock on the reentrant lock held by the application thread.

I think this is a regression of this change
https://github.com/ebean-orm/ebean-datasource/pull/12/files
I'm not sure, if we can safely remove the 'synchronized' there. because in my oppinion, notifyDataSourceDown/Up must be synchronized somehow. 
Maybe you have some minutes to take a look at this.

Cheers
Roland

**Comment by rbygrave** [comment]
Having a look now.  Good description, thanks.
