### ISSUE TITLE
More aggressive trimming on idle detection

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean-datasource#97]
Hello Rob,

we currently have a problem in our application, that connections are kept too long in the connection pool.

For your info, the application is a multi-tenant-per-db-app hosted on 6 application servers. We have one connection pool per tenant (and per server) with 2-20 connections and we have ~130 tenants. So this makes 12*130 idle connections.
There are 2 databases, each of them can provide up to 1500 connections.

We cannot make one connection pool per server, as every tenant has it's own connection string. The tenants are distributed equally to the two databases.

Now we have the following issue:

As long as the application is idle (weekend, no working hour) the amount of connections is ~12*130=1560

![grafik](https://github.com/ebean-orm/ebean-datasource/assets/5530228/2d043289-1c15-4ae3-a29f-e04adff45e80)

The problem begins, when the first users log in at 8:00 o'clock. Now the connection pools of the different tenants will increase. 
This is normally only a short peak.
We checked the code and found, that a trim on the connection pool occurs only, if one connection is inactive for more than 300 s (`maxInactiveTimeSecs=300` by default) - in our case, as the connections are in the pool, they are always reused and it takes a long time (nearly 8 h) until the CPs are trimmed to originial size.

We also found the `maxAgeMinutes` which may solve our current issue. But this will close also our min-connections, as long as I understand the code.

We might need a better solution for the future:
- a different strategy, when to trim idle connections (I want to shrink the pool more quickly to "minConnections" without closing them)
- long-term: a different connection-pool implementation (Pool of Pools?) that has a global upper limit for multi tenant environment 

Maybe you've some other ideas, how we can solve the problem?

Roland

**Comment by rbygrave** [comment]
> I want to shrink the pool more quickly to "minConnections" 

Reduce the maxInactiveTimeSecs from 300 ... to maybe 180?  When this is reduced then that likely means a lower hit ratio on PreparedStatements (so more "Hard parsing") so we are trading of "Less Idle Connections" with "More Hard Parsing Cost" + "More Connection Churn/Setup cost".  So imo be careful reducing that too much.

> without closing them

I don't understand that bit?  Trimming Idle connections closes them so I don't follow.

> long-term

There are server side pools like PG Bouncer and AWS RDS Proxy, so there might also be something like that for the database you are using here? Note that until recently these server side pools had issues with support for PreparedStatements, so until recently imo they really didn't help the situation per say BUT that has changed recently but take care evaluating a server side pool.

**Comment by rPraml** [comment]
Hello Rob,

> >    without closing them

> I don't understand that bit? Trimming Idle connections closes them so I don't follow.

Maybe I misunderstood the code. First I thought, when I obtain a new connection, a random connection of the pool is taken.
This means, they always get a new `usedSince`.
But as far as I see now, the [FreeConnectionBuffer](https://github.com/ebean-orm/ebean-datasource/blob/master/ebean-datasource/src/main/java/io/ebean/datasource/pool/FreeConnectionBuffer.java)
is a kind of stack, where the newest connection is always on top of the stack, so the old connections are at the bottom and are good candidates for `maxInactiveTimeSecs`

Some words to the setup

```
Tenant1  .. TenantN  (Each tenant has several users)
   |           |     (Network layer)
  [load-balancer]
         |
   [Tomcat-Farm]     (Currently 6 Tomcats)
    |         |
   [DB2 Cluster]     (2 DB2 instances, called LEFT and RIGHT)
```

- Currently ~130 active tenants. Planned 240 tenants
- The DB2 cluster can handle 2x3000 connections (formerly 2x1000)
- Even tenants using the left instance, odd the right
- We are using ebean in `TenantMode.DB_WITH_MASTER`. In the master DB there are the connection strings for the tenant-dbs.
- There is a TenantDataSourceProvider, that creates a connection pool for each tenant with 2-20 connection.
- Technically, the data for each tenant is partitioned in schemas, but each tenant connection has access only to the own schema

**What we have observed**
- In the morning, when users log in, a burst happens, because a lot of data is queuried for each user.
- These connections are only slowly trimmed.
- The problem is, when we do the math, that we have 130 tenants * 6 tomcats * 2 idle connections = 1560 idle connections.
- In the worst case, when each tenant and each tomcat uses all 20 connections, we would have 15600 and we run in the current connection limit of 6000 - with 240 tenants, there is a factor 4 again...

**What we did for now**
- We set the `maxAgeMinutes` to 5 minutes. This causes a faster reduction of open connections, but the DBA said that we are creating more connections per hour.
I agree, that `maxInactiveTimeSecs` should do the same, but javaMelody told us a different story.


**Further plans**
- Trying to improve the load balancing on the tomcats (Tenant 1 uses tomcat 1,3,5, Tenant 2 uses 2,3,4 or similar) - this prevents that each tomcat uses the max connection limit and gives us a factor 2
- Reduce the max connections per tenant from 20 to 10
- Add an additional DB2 cluster
- Take a look at server side connection pools

Maybe we have to reconsider the design decision, that we use a dedicated connection pool with own user and password for each tenant and maybe we have to use one technical user and two pools
(for left + right cluster side) or use `TenantMode.SCHEMA`

The pro arguments for `TenantMode.DB_WITH_MASTER` was, that we have a clear data separation and an additional security layer by the database, that tenant A cannot access data to tenant B

The con argument is, that it uses a lot of resources

We will further investigate and keep you up to date

Roland

**Comment by rbygrave** [comment]
> We set the maxAgeMinutes to 5 minutes

I don't think that is the correct knob and I think that is aggressively low. I'd definitely recommend reducing maxInactiveTimeSecs first.


> FreeConnectionBuffer is a kind of stack, where the newest connection is always on top of the stack, so the old connections are at the bottom and are good candidates for maxInactiveTimeSecs

It is LIFO (Last In First Out), meaning that it keeps busy connections busy and lets excess connections stay idle ... and those become candidates for `maxInactiveTimeSecs`.

`maxAgeMinutes` is literally max age regardless of how busy or how idle a connection is ... and therefore I'd call it "aggressive" because the PreparedStatements cache only lasts 5 minutes _regardless_ of how busy the system is. The preference is to use `maxInactiveTimeSecs` in order to have the preference to close Idle connections.  Older connections will have better PreparedStatement cache and we should prefer to keep these alive and in use.
